import React, { useState } from 'react';
import { Copy, Check, Search, Terminal, Code, Layers, FileText, ArrowRight, ShieldCheck } from 'lucide-react';
import { PROTO_CONTENT } from '../data/docsRegistry';

interface ProtoViewerProps {
  onSelectDoc?: (id: string) => void;
}

export const ProtoViewer: React.FC<ProtoViewerProps> = () => {
  const [activeTab, setActiveTab] = useState<'rpcs' | 'messages' | 'raw' | 'json-mapping'>('rpcs');
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);
  const [selectedRpc, setSelectedRpc] = useState<string>('SendMessage');

  const rpcList = [
    {
      name: 'SendMessage',
      path: '/message:send',
      method: 'POST',
      request: 'SendMessageRequest',
      response: 'SendMessageResponse',
      description: 'Sends a single message to an agent. Supports synchronous request-response task execution.',
      additionalBindings: ['/{tenant}/message:send'],
    },
    {
      name: 'SendStreamingMessage',
      path: '/message:stream',
      method: 'POST (Streaming)',
      request: 'SendMessageRequest',
      response: 'stream StreamResponse',
      description: 'Initiates real-time bidirectional or server-streaming interaction for task progress, chunks, and token delivery.',
      additionalBindings: ['/{tenant}/message:stream'],
    },
    {
      name: 'GetTask',
      path: '/tasks/{id=*}',
      method: 'GET',
      request: 'GetTaskRequest',
      response: 'Task',
      description: 'Retrieves the current execution status, artifacts, and history of a task by its unique ID.',
      additionalBindings: ['/{tenant}/tasks/{id=*}'],
    },
    {
      name: 'ListTasks',
      path: '/tasks',
      method: 'GET',
      request: 'ListTasksRequest',
      response: 'ListTasksResponse',
      description: 'Lists tasks matching optional filter conditions (state, client, time ranges).',
      additionalBindings: ['/{tenant}/tasks'],
    },
    {
      name: 'CancelTask',
      path: '/tasks/{id=*}:cancel',
      method: 'POST',
      request: 'CancelTaskRequest',
      response: 'Task',
      description: 'Cancels an in-progress or queued task.',
      additionalBindings: ['/{tenant}/tasks/{id=*}:cancel'],
    },
    {
      name: 'Subscribe',
      path: '/tasks/{id=*}:subscribe',
      method: 'POST (Server-Sent Events)',
      request: 'SubscribeRequest',
      response: 'stream StreamResponse',
      description: 'Subscribes to live lifecycle updates, status changes, and artifact outputs for an existing task.',
      additionalBindings: ['/{tenant}/tasks/{id=*}:subscribe'],
    },
  ];

  const messageDefinitions = [
    {
      name: 'Task',
      description: 'The core stateful unit of work executed by an agent.',
      fields: [
        { name: 'id', type: 'string', number: 1, desc: 'Unique identifier for the task.' },
        { name: 'session_id', type: 'string', number: 2, desc: 'Optional multi-turn conversation session id.' },
        { name: 'status', type: 'TaskStatus', number: 3, desc: 'Current state of the task (SUBMITTED, WORKING, COMPLETED, FAILED).' },
        { name: 'artifacts', type: 'repeated Artifact', number: 4, desc: 'Output data, files, or structured summaries generated by the task.' },
        { name: 'history', type: 'repeated Message', number: 5, desc: 'Message exchange history within this task.' },
        { name: 'metadata', type: 'google.protobuf.Struct', number: 6, desc: 'Arbitrary client/agent metadata.' },
      ],
    },
    {
      name: 'AgentCard',
      description: 'Self-describing manifest published at /.well-known/agent.json to declare agent capabilities, skills, and authentication.',
      fields: [
        { name: 'name', type: 'string', number: 1, desc: 'Human-readable name of the agent.' },
        { name: 'description', type: 'string', number: 2, desc: 'Detailed explanation of what the agent does and when to call it.' },
        { name: 'url', type: 'string', number: 3, desc: 'Base endpoint URL for the agent.' },
        { name: 'version', type: 'string', number: 4, desc: 'Semantic version of the agent.' },
        { name: 'skills', type: 'repeated AgentSkill', number: 5, desc: 'Specific capabilities and functions the agent can perform.' },
        { name: 'capabilities', type: 'AgentCapabilities', number: 6, desc: 'Supported protocols (streaming, async, push notifications).' },
        { name: 'security_schemes', type: 'repeated SecurityScheme', number: 7, desc: 'OAuth2, API keys, or mTLS requirements.' },
      ],
    },
    {
      name: 'Message',
      description: 'A message exchanged between agents or from client to agent.',
      fields: [
        { name: 'role', type: 'Role', number: 1, desc: 'ROLE_USER, ROLE_AGENT, or ROLE_SYSTEM.' },
        { name: 'parts', type: 'repeated Part', number: 2, desc: 'Ordered multimodal content parts (text, file, data).' },
        { name: 'created_at', type: 'google.protobuf.Timestamp', number: 3, desc: 'UTC timestamp when the message was sent.' },
        { name: 'metadata', type: 'google.protobuf.Struct', number: 4, desc: 'Custom message metadata.' },
      ],
    },
    {
      name: 'Part',
      description: 'A multimodal segment of a message (text, raw bytes, structured JSON, or tool calls).',
      fields: [
        { name: 'text', type: 'string', number: 1, desc: 'Plain text or markdown content.' },
        { name: 'raw', type: 'bytes', number: 2, desc: 'Raw binary data (e.g. image, PDF, audio).' },
        { name: 'structured', type: 'google.protobuf.Struct', number: 3, desc: 'Structured JSON data object.' },
        { name: 'media_type', type: 'string', number: 4, desc: 'MIME type of the part (e.g., text/plain, image/png, application/json).' },
      ],
    },
    {
      name: 'Artifact',
      description: 'A persistent result created during task execution (documents, generated code, reports).',
      fields: [
        { name: 'id', type: 'string', number: 1, desc: 'Unique artifact ID.' },
        { name: 'name', type: 'string', number: 2, desc: 'Name or filename of the artifact.' },
        { name: 'parts', type: 'repeated Part', number: 3, desc: 'Data content for the artifact.' },
        { name: 'created_at', type: 'google.protobuf.Timestamp', number: 4, desc: 'Timestamp of generation.' },
      ],
    },
  ];

  const handleCopy = () => {
    navigator.clipboard.writeText(PROTO_CONTENT);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const filteredMessages = messageDefinitions.filter(m =>
    m.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    m.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const activeRpcData = rpcList.find(r => r.name === selectedRpc) || rpcList[0];

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-neutral-200 dark:border-neutral-800 pb-6">
        <div>
          <div className="flex items-center gap-2 mb-1.5 font-mono">
            <span className="px-2 py-0.5 text-xs uppercase tracking-wider bg-neutral-100 dark:bg-neutral-900 text-neutral-800 dark:text-neutral-200 border border-neutral-200 dark:border-neutral-800 rounded">
              syntax = "proto3"
            </span>
            <span className="text-xs text-neutral-500">package lf.a2a.v1</span>
          </div>
          <h1 className="text-3xl font-extrabold text-neutral-900 dark:text-white tracking-tight">
            Protobuf & API Specification
          </h1>
          <p className="text-neutral-600 dark:text-neutral-400 text-sm mt-1">
            Normative schema defining gRPC services, HTTP/REST endpoints, message payloads, and Agent Cards.
          </p>
        </div>

        <button
          onClick={handleCopy}
          className="self-start sm:self-auto flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-medium text-neutral-800 dark:text-neutral-200 bg-white dark:bg-black border border-neutral-300 dark:border-neutral-700 hover:border-black dark:hover:border-white rounded-md transition-colors"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-neutral-900 dark:text-white" />
              <span className="font-semibold">Copied a2a.proto</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-neutral-400" />
              <span>Copy Full .proto File</span>
            </>
          )}
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-neutral-200 dark:border-neutral-800 space-x-2 sm:space-x-4 text-xs sm:text-sm font-medium">
        <button
          onClick={() => setActiveTab('rpcs')}
          className={`pb-3 px-2 border-b-2 flex items-center gap-2 transition-colors ${
            activeTab === 'rpcs'
              ? 'border-black text-black dark:border-white dark:text-white font-semibold'
              : 'border-transparent text-neutral-500 hover:text-black dark:hover:text-white'
          }`}
        >
          <Terminal className="w-4 h-4" />
          <span>A2AService RPCs (6)</span>
        </button>
        <button
          onClick={() => setActiveTab('messages')}
          className={`pb-3 px-2 border-b-2 flex items-center gap-2 transition-colors ${
            activeTab === 'messages'
              ? 'border-black text-black dark:border-white dark:text-white font-semibold'
              : 'border-transparent text-neutral-500 hover:text-black dark:hover:text-white'
          }`}
        >
          <Layers className="w-4 h-4" />
          <span>Core Messages</span>
        </button>
        <button
          onClick={() => setActiveTab('json-mapping')}
          className={`pb-3 px-2 border-b-2 flex items-center gap-2 transition-colors ${
            activeTab === 'json-mapping'
              ? 'border-black text-black dark:border-white dark:text-white font-semibold'
              : 'border-transparent text-neutral-500 hover:text-black dark:hover:text-white'
          }`}
        >
          <Code className="w-4 h-4" />
          <span>JSON Mapping (ADR-001)</span>
        </button>
        <button
          onClick={() => setActiveTab('raw')}
          className={`pb-3 px-2 border-b-2 flex items-center gap-2 transition-colors ${
            activeTab === 'raw'
              ? 'border-black text-black dark:border-white dark:text-white font-semibold'
              : 'border-transparent text-neutral-500 hover:text-black dark:hover:text-white'
          }`}
        >
          <FileText className="w-4 h-4" />
          <span>Raw a2a.proto</span>
        </button>
      </div>

      {/* Tab 1: RPCs */}
      {activeTab === 'rpcs' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* RPC selector list */}
          <div className="lg:col-span-4 space-y-2">
            <div className="text-[11px] font-bold uppercase font-mono text-neutral-400 mb-2">
              Select Endpoint / Method
            </div>
            {rpcList.map((rpc) => (
              <button
                key={rpc.name}
                onClick={() => setSelectedRpc(rpc.name)}
                className={`w-full text-left p-3 rounded-lg border transition-all ${
                  selectedRpc === rpc.name
                    ? 'border-black dark:border-white bg-neutral-100 dark:bg-neutral-900 text-black dark:text-white'
                    : 'border-neutral-200 dark:border-neutral-800 hover:bg-neutral-50 dark:hover:bg-neutral-900/50 text-neutral-700 dark:text-neutral-300'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono font-bold text-sm">{rpc.name}</span>
                  <span
                    className="text-[10px] font-mono px-1.5 py-0.5 rounded border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-black text-neutral-600 dark:text-neutral-300"
                  >
                    {rpc.method.split(' ')[0]}
                  </span>
                </div>
                <div className="text-xs font-mono text-neutral-500 mt-1 truncate">
                  {rpc.path}
                </div>
              </button>
            ))}
          </div>

          {/* Active RPC detail panel */}
          <div className="lg:col-span-8 border border-neutral-200 dark:border-neutral-800 rounded-lg bg-white dark:bg-black p-6 space-y-6">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="px-2 py-0.5 text-xs font-mono uppercase bg-neutral-100 dark:bg-neutral-900 text-neutral-800 dark:text-neutral-200 border border-neutral-200 dark:border-neutral-800 rounded">
                  rpc
                </span>
                <h2 className="text-xl font-mono font-bold text-neutral-900 dark:text-white">
                  {activeRpcData.name}
                </h2>
              </div>
              <p className="text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed">
                {activeRpcData.description}
              </p>
            </div>

            <div className="space-y-4">
              <h3 className="text-[11px] font-bold uppercase font-mono text-neutral-400">
                HTTP / REST Transcoding
              </h3>
              <div className="p-3 bg-neutral-950 text-neutral-100 rounded-lg font-mono text-xs space-y-1 border border-neutral-800">
                <div className="flex items-center gap-2">
                  <span className="text-white font-bold">{activeRpcData.method}</span>
                  <span className="text-neutral-300">{activeRpcData.path}</span>
                </div>
                {activeRpcData.additionalBindings.map((b, idx) => (
                  <div key={idx} className="text-neutral-400 pl-4 border-l border-neutral-800 text-[11px]">
                    Multi-tenant: {b}
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-lg bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800">
                <div className="text-[11px] font-bold uppercase font-mono text-neutral-400 mb-1">Request Payload</div>
                <div className="font-mono text-sm font-semibold text-neutral-900 dark:text-white">
                  {activeRpcData.request}
                </div>
              </div>
              <div className="p-4 rounded-lg bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800">
                <div className="text-[11px] font-bold uppercase font-mono text-neutral-400 mb-1">Response Payload</div>
                <div className="font-mono text-sm font-semibold text-neutral-900 dark:text-white">
                  {activeRpcData.response}
                </div>
              </div>
            </div>

            <div className="p-4 rounded-lg bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 text-xs text-neutral-700 dark:text-neutral-300 flex items-start gap-2.5">
              <ShieldCheck className="w-4 h-4 shrink-0 mt-0.5 text-neutral-500" />
              <div>
                <strong className="text-neutral-900 dark:text-white">A2A Security Standard:</strong> Agents accept incoming RPC calls validated against the security schemes declared in their <code>/.well-known/agent.json</code> Agent Card.
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Core Messages */}
      {activeTab === 'messages' && (
        <div className="space-y-6">
          <div className="flex items-center gap-2 px-3 py-2 bg-neutral-50 dark:bg-neutral-900 rounded-md border border-neutral-200 dark:border-neutral-800 max-w-md">
            <Search className="w-4 h-4 text-neutral-400" />
            <input
              type="text"
              placeholder="Filter message schemas (e.g. Task, Artifact, Part)..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-transparent border-none text-xs sm:text-sm text-neutral-900 dark:text-white placeholder-neutral-400 focus:outline-none w-full"
            />
          </div>

          <div className="grid grid-cols-1 gap-6">
            {filteredMessages.map((msg) => (
              <div
                key={msg.name}
                className="border border-neutral-200 dark:border-neutral-800 rounded-lg bg-white dark:bg-black p-5"
              >
                <div className="flex items-center gap-2 mb-2">
                  <span className="font-mono text-xs px-2 py-0.5 bg-neutral-100 dark:bg-neutral-900 text-neutral-800 dark:text-neutral-200 border border-neutral-200 dark:border-neutral-800 rounded">
                    message
                  </span>
                  <h3 className="font-mono text-lg font-bold text-neutral-900 dark:text-white">
                    {msg.name}
                  </h3>
                </div>
                <p className="text-sm text-neutral-600 dark:text-neutral-400 mb-4">{msg.description}</p>

                <div className="overflow-x-auto border border-neutral-200 dark:border-neutral-800 rounded-lg">
                  <table className="w-full text-xs">
                    <thead className="bg-neutral-50 dark:bg-neutral-900 text-neutral-500 uppercase font-mono">
                      <tr>
                        <th className="px-3 py-2 text-left">Tag #</th>
                        <th className="px-3 py-2 text-left">Field Name</th>
                        <th className="px-3 py-2 text-left">Type</th>
                        <th className="px-3 py-2 text-left font-sans">Description</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-neutral-100 dark:divide-neutral-800 font-mono">
                      {msg.fields.map((field) => (
                        <tr key={field.name} className="hover:bg-neutral-50/50 dark:hover:bg-neutral-900/50">
                          <td className="px-3 py-2 text-neutral-400">{field.number}</td>
                          <td className="px-3 py-2 font-bold text-neutral-900 dark:text-white">{field.name}</td>
                          <td className="px-3 py-2 text-neutral-600 dark:text-neutral-300 font-semibold">{field.type}</td>
                          <td className="px-3 py-2 font-sans text-neutral-600 dark:text-neutral-400">{field.desc}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab 3: JSON Mapping Guide */}
      {activeTab === 'json-mapping' && (
        <div className="border border-neutral-200 dark:border-neutral-800 rounded-lg bg-white dark:bg-black p-6 space-y-6">
          <div>
            <h2 className="text-xl font-bold text-neutral-900 dark:text-white mb-2">
              ProtoJSON Serialization (ADR-001)
            </h2>
            <p className="text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed">
              When A2A messages are transmitted over HTTP/1.1 or HTTP/2 as JSON, they adhere strictly to standard Protobuf-to-JSON mapping conventions:
            </p>
          </div>

          <div className="space-y-4">
            <div className="p-4 rounded-lg bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800">
              <h3 className="font-semibold text-sm text-neutral-900 dark:text-white mb-2">
                Key Serialization Rules:
              </h3>
              <ul className="text-xs text-neutral-600 dark:text-neutral-400 space-y-2 list-disc pl-5">
                <li>
                  <strong>Field Naming:</strong> Field names in JSON must use <code>camelCase</code> by default (e.g., <code>sessionId</code>, <code>createdAt</code>) unless preserve_proto_field_names is explicitly set.
                </li>
                <li>
                  <strong>Enum Values:</strong> Enums are serialized as string names (e.g. <code>"ROLE_AGENT"</code>, <code>"STATUS_COMPLETED"</code>), NOT raw integers.
                </li>
                <li>
                  <strong>64-bit Integers:</strong> int64 and uint64 are encoded as strings (e.g., <code>"123456789"</code>) to prevent JavaScript precision loss.
                </li>
                <li>
                  <strong>Timestamps:</strong> <code>google.protobuf.Timestamp</code> values are encoded as ISO 8601 strings (e.g., <code>"2026-09-13T12:00:00Z"</code>).
                </li>
                <li>
                  <strong>Bytes:</strong> Binary fields are base64-encoded strings.
                </li>
              </ul>
            </div>

            <div className="p-4 bg-neutral-950 rounded-lg text-neutral-100 font-mono text-xs border border-neutral-800">
              <div className="text-neutral-500 mb-2">// Example A2A Task JSON payload:</div>
              <pre className="overflow-x-auto text-neutral-200">
{`{
  "id": "task-8f3a9e21",
  "sessionId": "sess-alpha-001",
  "status": "STATUS_COMPLETED",
  "history": [
    {
      "role": "ROLE_USER",
      "parts": [
        {
          "text": "Book hotel in Kyoto for 3 nights starting October 10.",
          "mediaType": "text/plain"
        }
      ]
    },
    {
      "role": "ROLE_AGENT",
      "parts": [
        {
          "text": "Confirmed reservation at Kyoto Garden Hotel.",
          "mediaType": "text/plain"
        }
      ]
    }
  ],
  "artifacts": [
    {
      "id": "art-kyoto-voucher",
      "name": "booking_confirmation.json",
      "parts": [
        {
          "structured": {
            "hotel": "Kyoto Garden Hotel",
            "nights": 3,
            "checkIn": "2026-10-10",
            "reference": "KG-99218"
          },
          "mediaType": "application/json"
        }
      ]
    }
  ]
}`}
              </pre>
            </div>
          </div>
        </div>
      )}

      {/* Tab 4: Raw .proto */}
      {activeTab === 'raw' && (
        <div className="rounded-lg border border-neutral-200 dark:border-neutral-800 bg-neutral-950 text-neutral-100 overflow-hidden">
          <div className="flex items-center justify-between px-4 py-2 bg-black border-b border-neutral-800 text-xs text-neutral-400 font-mono">
            <span>specification/a2a.proto (813 lines)</span>
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-neutral-900 hover:bg-neutral-800 text-neutral-300 hover:text-white transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
          </div>
          <pre className="p-4 overflow-x-auto text-xs font-mono leading-relaxed max-h-[650px] overflow-y-auto text-neutral-200">
            <code>{PROTO_CONTENT}</code>
          </pre>
        </div>
      )}
    </div>
  );
};
